package com.expensetracker.ui.screens

import android.content.Context
import android.content.Intent
import com.expensetracker.data.model.ExpenseStats
import com.expensetracker.data.model.TransactionCategory
import java.text.NumberFormat
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import java.util.Locale

object ShareReportHelper {

    private val currencyFormat = NumberFormat.getCurrencyInstance(Locale("en", "IN"))

    private fun getCategoryEmoji(category: TransactionCategory): String {
        return when (category) {
            TransactionCategory.FOOD_DINING -> "🍔"
            TransactionCategory.GROCERIES -> "🛒"
            TransactionCategory.TRANSPORT -> "🚗"
            TransactionCategory.SHOPPING -> "🛍️"
            TransactionCategory.BILLS_UTILITIES -> "📄"
            TransactionCategory.ENTERTAINMENT -> "🎬"
            TransactionCategory.HEALTH -> "🏥"
            TransactionCategory.EDUCATION -> "📚"
            TransactionCategory.SALARY -> "💵"
            TransactionCategory.SAVINGS -> "💰"
            TransactionCategory.TRANSFER -> "🔄"
            TransactionCategory.ATM_WITHDRAWAL -> "🏧"
            TransactionCategory.EMI -> "💳"
            TransactionCategory.SUBSCRIPTION -> "🔁"
            TransactionCategory.FUEL -> "⛽"
            TransactionCategory.TRAVEL -> "✈️"
            TransactionCategory.OTHER -> "💸"
        }
    }

    fun generateReportText(stats: ExpenseStats): String {
        val now = LocalDateTime.now()
        val monthYear = now.format(DateTimeFormatter.ofPattern("MMMM yyyy"))
        val balance = stats.totalIncome - stats.totalSpent

        val sb = StringBuilder()
        sb.appendLine("📊 AutoExpense Monthly Report - $monthYear")
        sb.appendLine()
        sb.appendLine("💰 Total Spent: ${currencyFormat.format(stats.totalSpent)}")
        sb.appendLine("📈 Total Income: ${currencyFormat.format(stats.totalIncome)}")
        sb.appendLine("💵 Balance: ${currencyFormat.format(balance)}")

        if (stats.categoryBreakdown.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("📋 Category Breakdown:")

            val sortedCategories = stats.categoryBreakdown.entries
                .sortedByDescending { it.value }

            val totalCategorySpend = sortedCategories.sumOf { it.value }

            sortedCategories.take(8).forEach { (category, amount) ->
                val percentage = if (totalCategorySpend > 0) {
                    ((amount / totalCategorySpend) * 100).toInt()
                } else 0
                val emoji = getCategoryEmoji(category)
                sb.appendLine("$emoji ${category.displayName}: ${currencyFormat.format(amount)} ($percentage%)")
            }
        }

        if (stats.topMerchants.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("🏪 Top Merchants:")
            stats.topMerchants.take(5).forEachIndexed { index, merchant ->
                sb.appendLine("${index + 1}. ${merchant.name} - ${currencyFormat.format(merchant.totalSpent)}")
            }
        }

        sb.appendLine()
        sb.appendLine("Generated by AutoExpense")

        return sb.toString()
    }

    fun shareReport(context: Context, stats: ExpenseStats) {
        val reportText = generateReportText(stats)
        val sendIntent = Intent().apply {
            action = Intent.ACTION_SEND
            putExtra(Intent.EXTRA_TEXT, reportText)
            type = "text/plain"
        }
        val shareIntent = Intent.createChooser(sendIntent, "Share Monthly Report")
        shareIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        context.startActivity(shareIntent)
    }
}
